---
- name: Install Docker on the Yandex Cloud VM
  hosts: all
  become: true

  tasks:
    - name: Gather facts about the system
      ansible.builtin.setup:

    - name: Install required dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker repository
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] | lower }} stable"
        state: present

    - name: Add Docker repository GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes
